import asyncpg
from datetime import date

class Database:
    def __init__(self, pool):
        self.pool = pool

    async def create_tables(self):
        '''
        Creates tables, if they aren't on database
        (in simple words, it's database initialisation)
        '''
        async with self.pool.acquire() as conn:
            await conn.execute('''CREATE TABLE IF NOT EXISTS users_table (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id bigint NOT NULL UNIQUE,
                       username varchar(255) NOT NULL,
                       name varchar(255) NOT NULL,
                       surname varchar(255),
                       birthdate DATE
                       )''')
            await conn.execute('''CREATE TABLE IF NOT EXISTS groups_table (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       group_id bigint NOT NULL UNIQUE,
                       group_name varchar(255) NOT NULL
                       )''')
            await conn.execute('''CREATE TABLE IF NOT EXISTS users_groups (
                       user_id_db int REFERENCES users_table(id) ON DELETE CASCADE,
                       group_id_db int REFERENCES groups_table(id) ON DELETE CASCADE,
                       allow_call boolean NOT NULL DEFAULT TRUE,
                       hide_birthdate boolean NOT NULL DEFAULT FALSE,
                       PRIMARY KEY (user_id_db, group_id_db)
                       )''')
    
    async def add_group(self, groupid: int, grouptitle: str):
        '''
        Quick add group into database
        '''
        async with self.pool.acquire() as conn:
            await conn.execute('''INSERT INTO groups_table (group_id, group_name)
                                   VALUES ($1, $2)
                                   ON CONFLICT (group_id) DO 
                                   UPDATE SET group_name = EXCLUDED.group_name''',
                                   groupid, grouptitle)

    async def create_rows(self, users: list, groupid: int, grouptitle: str):
        '''
        Creates rows of all users
        (calls when added into group ftft)
        NOTE: only list of tuples: [(user_id, username, name, surname, birthdate)]
        p.s. make sure that these conditions are validated BEFORE this func.
        NOTE: allow_call is always True (alt desc - is user a bot)
        '''
        async with self.pool.acquire() as conn:
            async with conn.transaction():
                await conn.execute('''INSERT INTO groups_table (group_id, group_name)
                                   VALUES ($1, $2)
                                   ON CONFLICT (group_id) DO 
                                   UPDATE SET group_name = EXCLUDED.group_name''',
                                   groupid, grouptitle)
                await conn.executemany('''INSERT INTO users_table
                                       (user_id, username, name, surname, birthdate) VALUES
                                       ($1, $2, $3, $4, $5)
                                       ON CONFLICT (user_id) DO NOTHING''',
                                       users)
                await conn.executemany('''INSERT INTO users_groups (user_id_db, group_id_db)
                                       SELECT u.id, g.id
                                       FROM users_table u, groups_table g
                                       WHERE u.user_id = $1 AND g.group_id = $2
                                       ON CONFLICT DO NOTHING''',
                                       [(user[0], groupid) for user in users])
    async def change_birthdate(self, userid: int, birthdate: date):
        '''
        Changes birthdate of specific user
        '''
        async with self.pool.acquire() as conn:
            await conn.execute('''UPDATE users_table
                               SET birthdate = $1
                               WHERE user_id = $2''',
                               birthdate, userid)
    async def get_birthdate(self, userid: int):
        '''
        Returns birthdate
        '''
        async with self.pool.acquire() as conn:
            birthdate = await conn.fetchval('''SELECT birthdate
                                            FROM users_table
                                            WHERE user_id = $1''',
                                            userid)
            return birthdate
    async def get_today_birthdays(self):
        '''
        Returns list of tuples if there's birthday today
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT u.user_id, g.group_id, u.name, u.username
                                    FROM users_table u
                                    JOIN users_groups ug ON u.id = ug.user_id_db
                                    JOIN groups_table g ON g.id = ug.group_id_db
                                    WHERE
                                        EXTRACT(MONTH FROM u.birthdate) = EXTRACT(MONTH FROM CURRENT_DATE)
                                        AND
                                        EXTRACT(DAY FROM u.birthdate) = EXTRACT(DAY FROM CURRENT_DATE)
                                        AND ug.hide_birthdate = FALSE''')
    async def get_tomorrow_reminders(self):
        '''
        Odd function. Returns list of tuples all of the people
        EXCEPT person that has birthday tomorrow
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT
                                        recip.user_id AS recipid,
                                        recip.name AS recipname,
                                        bday_person.name AS bdayname,
                                        groups.group_name AS grouptitle
                                    FROM users_table bday_person
                                    JOIN users_groups ug_bday ON bday_person.id = ug_bday.user_id_db
                                    JOIN groups_table groups ON ug_bday.group_id_db = groups.id
                                    JOIN users_groups ug_recip ON groups.id = ug_recip.group_id_db
                                    JOIN users_table recip ON ug_recip.user_id_db = recip.id
                                    WHERE
                                        EXTRACT(MONTH FROM bday_person.birthdate) = EXTRACT(MONTH FROM CURRENT_DATE + INTERVAL '1 DAY')
                                        AND
                                        EXTRACT(DAY FROM bday_person.birthdate) = EXTRACT(DAY FROM CURRENT_DATE + INTERVAL '1 DAY')
                                        AND recip.id != bday_person.id
                                        AND ug_bday.hide_birthdate = FALSE''')
    async def get_user_groups(self, userid: int):
        '''
        Returns list of groups, where bot and user are exist
        [(group_id_db, group_title), ...]
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT g.id, g.group_name AS group_title
                                    FROM groups_table g
                                    JOIN users_groups ug ON g.id = ug.group_id_db
                                    JOIN users_table u ON ug.user_id_db = u.id
                                    WHERE u.user_id = $1''', 
                                    userid)
    async def get_group_birthdays(self, groupid: int):
        '''
        Return list of people's birthdays from exact group,
        sorted by date
        [(name, surname, username, birthdate), ...]
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT u.name, u.surname, u.username, u.birthdate
                                    FROM users_table u
                                    JOIN users_groups ug ON u.id = ug.user_id_db
                                    WHERE
                                        ug.group_id_db = $1
                                        AND u.birthdate IS NOT NULL
                                        AND ug.hide_birthdate = FALSE
                                    ORDER BY
                                        EXTRACT(MONTH FROM u.birthdate),
                                        EXTRACT(DAY FROM u.birthdate)''',
                                    groupid)
    async def get_user_groups_settings(self, userid: int):
        '''
        Returns list of groups where user exists with hide_birthdate option
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT g.id, g.group_name, ug.hide_birthdate
                                    FROM groups_table g
                                    JOIN users_groups ug ON g.id = ug.group_id_db
                                    JOIN users_table u ON ug.user_id_db = u.id
                                    WHERE u.user_id = $1''',
                                    userid)
    async def toggle_hide_status(self, userid: int, groupid: int):
        '''
        Changes hide status: False->True and vise versa.
        '''
        async with self.pool.acquire() as conn:
            await conn.fetchval('''UPDATE users_groups ug 
                                SET hide_birthdate = NOT hide_birthdate 
                                FROM users_table u
                                WHERE
                                    ug.user_id_db = u.id
                                    AND ug.group_id_db = $2
                                    AND u.user_id = $1''',
                                userid, groupid)
    async def get_birthdays_by_chatid(self, chatid: int):
        '''
        Same as get_group_birthdays, but with Telegram ID (-1001488...)
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT u.name, u.surname, u.username, u.birthdate
                                    FROM users_table u
                                    JOIN users_groups ug ON u.id = ug.user_id_db
                                    JOIN groups_table g ON g.id = ug.group_id_db
                                    WHERE
                                        g.group_id = $1
                                        AND u.birthdate IS NOT NULL
                                        AND ug.hide_birthdate = FALSE
                                    ORDER BY
                                        EXTRACT(MONTH FROM u.birthdate),
                                        EXTRACT(DAY FROM u.birthdate)''',
                                        chatid)
    async def set_call(self, userid: int, groupid: int, status: bool):
        '''
        Sets user's reg status in certain group 
        '''
        async with self.pool.acquire() as conn:
            await conn.execute('''UPDATE users_groups ug
                               SET allow_call = $3
                               FROM users_table u, groups_table g
                               WHERE
                                    ug.user_id_db = u.id
                                    AND ug.group_id_db = g.id
                                    AND u.user_id = $1
                                    AND g.group_id = $2''',
                                    userid, groupid, status)
    async def get_call_regs(self, groupid: int):
        '''
        Returns list of users (user_id) which have 'reg' in group
        '''
        async with self.pool.acquire() as conn:
            return await conn.fetch('''SELECT u.user_id
                                      FROM users_table u
                                      JOIN users_groups ug ON u.id = ug.user_id_db
                                      JOIN groups_table g ON ug.group_id_db = g.id
                                      WHERE
                                        g.group_id = $1
                                        AND ug.allow_call = TRUE''',
                                        groupid)
    async def remove_user(self, userid: int, groupid: int):
        '''
        Deletes link between user and group.
        NOTE: this func does NOT delete the user from users_table.
        '''
        async with self.pool.acquire() as conn:
            await conn.execute('''DELETE FROM users_groups
                               WHERE user_id_db = (SELECT id FROM users_table WHERE user_id = $1)
                               AND group_id_db = (SELECT id FROM groups_table WHERE group_id = $2)''',
                               userid, groupid)